name = "JuliaTutorial"
uuid = "1d3b2fbe-cc7e-4cae-ba11-5160a753e715"
authors = ["Matthew Schlegel <mkschleg@gmail.com>"]
version = "0.1.0"

[deps]
EllipsisNotation = "da5c29d0-fa7d-589e-88eb-ea29b0a81949"
